volumes:
  pg_data:

services:
  db:
    image: postgres:16
    env_file: .env
    hostname: userbot_pg
    volumes:
      - pg_data:/var/lib/postgresql/data
  bot:
    build: ../bot/
    depends_on:
      - db
    env_file: .env
    environment:
      WAIT_HOSTS: userbot_pg:5432
