"""Add field msg_num_to_recieve to profiles

Revision ID: d523a94490d5
Revises: d181d2302032
Create Date: 2024-05-20 01:07:17.474453

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d523a94490d5"
down_revision: Union[str, None] = "d181d2302032"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "msg_num_to_recieve",
            sa.Enum("FIRST", "SECOND", "THIRD", name="msgnum"),
            server_default="FIRST",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "msg_num_to_recieve")
    # ### end Alembic commands ###
